export type SeedCategory = "Design" | "Work" | "Life" | "Culture" | "Academic";
export type SeedLevel = "B1" | "B2" | "C1";

export type SeedActivity = {
  id: string;
  title: string;
  publisher: string;
  sourceUrl: string;
  category: SeedCategory;
  level: SeedLevel;
  minutes: 5 | 15 | 30;
  skills: string[];
  usageBasis: string;
  prompt: string;
  output: string;
  reviewedAt: string;
};

const LINK_BASIS = "Publisher-hosted page; LUCID DREAM stores only metadata and original study prompts.";

export const SEED_LIBRARY: readonly SeedActivity[] = [
  { id: "apple-design-principles", title: "Principles of great design", publisher: "Apple Developer", sourceUrl: "https://developer.apple.com/videos/design/", category: "Design", level: "B2", minutes: 15, skills: ["Listening", "Design vocabulary"], usageBasis: LINK_BASIS, prompt: "Listen for three qualities used to evaluate a design.", output: "Give a 60-second Design Breakdown of one interface you use.", reviewedAt: "2026-08-18" },
  { id: "apple-ux-writing", title: "Make a big impact with small writing changes", publisher: "Apple Developer", sourceUrl: "https://developer.apple.com/videos/design/", category: "Design", level: "B2", minutes: 15, skills: ["Listening", "UX writing"], usageBasis: LINK_BASIS, prompt: "Notice how short interface labels reduce uncertainty.", output: "Rewrite three labels from one of your projects in English.", reviewedAt: "2026-08-18" },
  { id: "apple-inclusive-design", title: "Principles of inclusive app design", publisher: "Apple Developer", sourceUrl: "https://developer.apple.com/videos/design/", category: "Design", level: "C1", minutes: 30, skills: ["Listening", "Accessibility"], usageBasis: LINK_BASIS, prompt: "Identify one design decision that includes more users.", output: "Explain an accessibility improvement for your portfolio project.", reviewedAt: "2026-08-18" },
  { id: "apple-presenting-work", title: "Presenting design work", publisher: "Apple Developer", sourceUrl: "https://developer.apple.com/videos/design/", category: "Design", level: "B2", minutes: 15, skills: ["Listening", "Presentation"], usageBasis: LINK_BASIS, prompt: "Track the order used to move from context to decision.", output: "Record a 60-second opening for your own case study.", reviewedAt: "2026-08-18" },
  { id: "figma-future-apps", title: "Design for the future of apps", publisher: "Figma Config", sourceUrl: "https://config.figma.com/san-francisco/session/d942bacb-600a-437f-817a-6d61794a930d/", category: "Design", level: "C1", minutes: 30, skills: ["Listening", "Design systems"], usageBasis: LINK_BASIS, prompt: "Listen for the tension between personalization and consistency.", output: "Write a six-sentence Design Breakdown with one trade-off.", reviewedAt: "2026-08-18" },
  { id: "figma-config-agenda", title: "Choose a Config design-systems talk", publisher: "Figma Config", sourceUrl: "https://config.figma.com/san-francisco/agenda/", category: "Design", level: "B2", minutes: 15, skills: ["Scanning", "Topic selection"], usageBasis: LINK_BASIS, prompt: "Scan titles and choose one talk relevant to your portfolio direction.", output: "Predict three ideas the speaker may cover, in English.", reviewedAt: "2026-08-18" },
  { id: "mit-computational-media", title: "Fundamentals of Computational Media Design", publisher: "MIT OpenCourseWare", sourceUrl: "https://ocw.mit.edu/courses/mas-110-fundamentals-of-computational-media-design-fall-2008/pages/syllabus/", category: "Design", level: "C1", minutes: 15, skills: ["Reading", "Media theory"], usageBasis: LINK_BASIS, prompt: "Find how the course connects art, technology, and critique.", output: "Describe where art and technology meet in one of your projects.", reviewedAt: "2026-08-18" },
  { id: "mit-media-assignment", title: "Reflect on a computational media process", publisher: "MIT OpenCourseWare", sourceUrl: "https://ocw.mit.edu/courses/mas-110-fundamentals-of-computational-media-design-fall-2008/pages/assignments/", category: "Design", level: "C1", minutes: 30, skills: ["Reading", "Reflection"], usageBasis: LINK_BASIS, prompt: "Look at how an assignment asks students to explain intention and process.", output: "Draft a short process reflection for your own work.", reviewedAt: "2026-08-18" },
  { id: "mit-sociable-media", title: "Designing sociable media", publisher: "MIT OpenCourseWare", sourceUrl: "https://ocw.mit.edu/courses/mas-961-special-topics-designing-sociable-media-spring-2008/", category: "Design", level: "C1", minutes: 15, skills: ["Reading", "Interaction design"], usageBasis: LINK_BASIS, prompt: "List two ways an interface represents social activity.", output: "Propose one social interaction and explain its visual feedback.", reviewedAt: "2026-08-18" },
  { id: "material-design", title: "Explore Material Design", publisher: "Google", sourceUrl: "https://m3.material.io/", category: "Design", level: "B2", minutes: 15, skills: ["Reading", "Design systems"], usageBasis: LINK_BASIS, prompt: "Choose one component and notice how guidance is structured.", output: "Explain when you would and would not use that component.", reviewedAt: "2026-08-18" },
  { id: "mit-digital-storytelling", title: "Media technology and city design", publisher: "MIT OpenCourseWare", sourceUrl: "https://ocw.mit.edu/courses/11-310j-media-technology-and-city-design-and-development-fall-2002/", category: "Academic", level: "C1", minutes: 30, skills: ["Reading", "Synthesis"], usageBasis: LINK_BASIS, prompt: "Identify how digital storytelling can represent a place.", output: "Pitch a small media project about a neighbourhood you know.", reviewedAt: "2026-08-18" },
  { id: "mit-visual-arguments", title: "Planning, communications, and digital media", publisher: "MIT OpenCourseWare", sourceUrl: "https://ocw.mit.edu/courses/11-204-planning-communications-and-digital-media-fall-2004/pages/lecture-notes/", category: "Academic", level: "C1", minutes: 30, skills: ["Reading", "Critical thinking"], usageBasis: LINK_BASIS, prompt: "Look for ways images can construct an argument about a place.", output: "Explain one ethical risk in visual storytelling.", reviewedAt: "2026-08-18" },
  { id: "mit-codesign", title: "Civic media codesign studio", publisher: "MIT OpenCourseWare", sourceUrl: "https://ocw.mit.edu/courses/cms-362-civic-media-codesign-studio-fall-2020/", category: "Academic", level: "C1", minutes: 15, skills: ["Reading", "Codesign"], usageBasis: LINK_BASIS, prompt: "Find the stages where communities participate in design.", output: "Summarize why codesign changes a designer's role.", reviewedAt: "2026-08-18" },
  { id: "skillsfuture-framework", title: "Map a Singapore skills framework", publisher: "SkillsFuture Singapore", sourceUrl: "https://www.skillsfuture.gov.sg/skills-framework", category: "Work", level: "B2", minutes: 15, skills: ["Scanning", "Career English"], usageBasis: LINK_BASIS, prompt: "Choose one sector and note three capabilities it values.", output: "Say which capability your portfolio already proves.", reviewedAt: "2026-08-18" },
  { id: "mom-ep", title: "Read an official Employment Pass requirement page", publisher: "Singapore Ministry of Manpower", sourceUrl: "https://www.mom.gov.sg/passes-and-permits/employment-pass/eligibility", category: "Work", level: "C1", minutes: 15, skills: ["Reading", "Policy vocabulary"], usageBasis: LINK_BASIS, prompt: "Separate candidate requirements from employer-dependent factors.", output: "Explain one limitation of making a visa plan too early.", reviewedAt: "2026-08-18" },
  { id: "mom-sat", title: "Understand the official Self-Assessment Tool", publisher: "Singapore Ministry of Manpower", sourceUrl: "https://www.mom.gov.sg/eservices/services/employment-s-pass-self-assessment-tool", category: "Work", level: "C1", minutes: 5, skills: ["Reading", "Practical English"], usageBasis: LINK_BASIS, prompt: "Find who the tool is designed for and what it cannot guarantee.", output: "Summarize the limitation in two English sentences.", reviewedAt: "2026-08-18" },
  { id: "singapore-digital", title: "Explore Singapore's digital economy direction", publisher: "IMDA", sourceUrl: "https://www.imda.gov.sg/about-imda/research-and-statistics/sgdigital/digital-economy-framework-for-action", category: "Work", level: "C1", minutes: 15, skills: ["Reading", "Industry vocabulary"], usageBasis: LINK_BASIS, prompt: "Scan for sectors and skills connected to digital work.", output: "Connect one trend to a digital-media portfolio project.", reviewedAt: "2026-08-18" },
  { id: "ielts-speaking-criteria", title: "Read the IELTS Speaking criteria", publisher: "IELTS", sourceUrl: "https://ielts.org/cdn/ielts-guides/ielts-speaking-key-assessment-criteria.pdf", category: "Academic", level: "B2", minutes: 15, skills: ["Reading", "Exam literacy"], usageBasis: LINK_BASIS, prompt: "Choose one criterion and translate it into an observable habit.", output: "Record a response while focusing on that single habit.", reviewedAt: "2026-08-18" },
  { id: "ielts-sample", title: "Explore official IELTS sample questions", publisher: "IELTS", sourceUrl: "https://ielts.org/take-a-test/preparation-resources/sample-test-questions", category: "Academic", level: "B2", minutes: 15, skills: ["Reading", "Exam format"], usageBasis: LINK_BASIS, prompt: "Choose one section and identify what the task actually asks you to do.", output: "Write one strategy sentence and one warning sentence.", reviewedAt: "2026-08-18" },
  { id: "moma-magazine", title: "Read one MoMA design story", publisher: "MoMA", sourceUrl: "https://www.moma.org/magazine/", category: "Culture", level: "C1", minutes: 15, skills: ["Reading", "Art vocabulary"], usageBasis: LINK_BASIS, prompt: "Choose an article and notice how the writer frames context.", output: "Give a 60-second response: what changed how you saw the work?", reviewedAt: "2026-08-18" },
  { id: "tate-art-terms", title: "Build an art-language mini glossary", publisher: "Tate", sourceUrl: "https://www.tate.org.uk/art/art-terms", category: "Culture", level: "B1", minutes: 15, skills: ["Reading", "Vocabulary"], usageBasis: LINK_BASIS, prompt: "Pick three terms relevant to your visual style.", output: "Use each term in a sentence about your own work.", reviewedAt: "2026-08-18" },
  { id: "smithsonian-open", title: "Curate a three-object visual story", publisher: "Smithsonian", sourceUrl: "https://www.si.edu/openaccess", category: "Culture", level: "B2", minutes: 30, skills: ["Browsing", "Curation"], usageBasis: "Official Open Access portal; follow each asset's rights statement and store only original notes here.", prompt: "Choose three openly available objects with a shared visual idea.", output: "Present the three-object story in English.", reviewedAt: "2026-08-18" },
  { id: "nhs-appointment", title: "Understand how a GP appointment works", publisher: "NHS", sourceUrl: "https://www.nhs.uk/nhs-services/gps/gp-appointments-and-bookings/", category: "Life", level: "B2", minutes: 15, skills: ["Reading", "Life English"], usageBasis: LINK_BASIS, prompt: "Find the words used for booking and preparing for an appointment.", output: "Practise a short appointment request without inventing symptoms.", reviewedAt: "2026-08-18" },
  { id: "singapore-renting", title: "Read Singapore consumer guidance", publisher: "CASE Singapore", sourceUrl: "https://www.case.org.sg/", category: "Life", level: "C1", minutes: 15, skills: ["Scanning", "Consumer vocabulary"], usageBasis: LINK_BASIS, prompt: "Find one official channel for a consumer question or complaint.", output: "Draft a calm request for clarification and a specific remedy.", reviewedAt: "2026-08-18" },
];
